name    'get/limits'
version '2.0.10'
author  'GET-Automation'
license 'Apache2'
project_page 'https://github.comcast.com/GETAutomation/'
source 'https://github.comcast.com/GETAutomation/puppet-limits'
summary 'Puppet module for limits'
description 'This module installs and manages limits. Check README for details.'
dependency 'get/getlib'
